### ISSUE TITLE
separate prepare functions

### ISSUE THREAD

**Issue by doowb** [gulpjs/vinyl-prepare#15]
@phated I like what you did with the recent changes.

Would you be opposed to moving the `normalize` functions into other files so we can use them directly instead of in a stream?

```js
var dest = require('vinyl-prepare/dest');
```

We have use cases where we want to update the file properties outside of a stream.
If you're fine with this, I'll send a PR (I already see the code in my head ;)). This will address #9 also.

**Comment by phated** [comment]
I'm still unsure how I feel about everything.  By splitting this project once more, it doesn't seem to make sense to have it a stream interface at all.  If you don't mind waiting a little while, I'd like to do a full pass at refactoring vinyl-fs and see if I can't come to a better solution for everyone.

My only open question is: Are you trying to fit this into sync usage or would a callback interface work (to avoid try/catch)?

**Comment by doowb** [comment]
I think the api and interface are fine for this project so it can be used in `vinyl-fs` and I don't want to split it into any other projects. I'd like to be able to use the `normalize` functions directly so I can apply the normalization to an individual file.

I was thinking the main `index.js` file would look something like this:

```js
'use strict';

var through = require('through2');

var normalizeSrc = require('./src');
var normalizeDest = require('./dest');

function src(opt) {
  if (!opt) {
    opt = {};
  }

  function normalize(globFile, enc, callback) {
    return normalizeSrc(globFile, opt, callback);
  }
  return through.obj(normalize);
}

function dest(outFolder, opt) {
  if (!opt) {
    opt = {};
  }

  if (!outFolder) {
    throw new Error('Invalid output folder');
  }

  function normalize(file, enc, cb) {
    return normalizeDest(file, outFolder, opt, cb);
  }
  return through.obj(normalize);
}

module.exports = {
  src: src,
  dest: dest,
};
```

Those wouldn't even need to be in other files if they're exported along with the main function. I was thinking along the lines of what we just did in `object.defaults` for the `immutable` function.

> My only open question is: Are you trying to fit this into sync usage or would a callback interface work (to avoid try/catch)?

At first, I started doing that as a sync function because all of the operations inside the normalize functions are sync, but I see what you mean by the callback syntax for reducing the `try/catch`.

I'd prefer to be able to use them `sync` and just catch the errors if necessary (again because there are no async operations internally). Even if it's something like doing:

```js
if (since === null) {
  var err = new Error('Invalid since option');
  if (typeof callback === 'function') {
    return callback(err);
  }
  throw err;
}
```
I think that would work for both cases and you have an option of using the callback to reduce the need for a `try/catch` based on how it's being used.

**Comment by phated** [comment]
I think throwing is a really poor interface.

**Comment by doowb** [comment]
Okay... that's why I'm offering an alternative that allows passing in a callback.

Now that I'm looking at it more closely, it looks like the calls to the `value-of-function` methods should be wrapped with `try/catch` to ensure any errors from user-defined functions are caught and passed to the stream's callback.

Making those normalize methods sync and handling errors with a `try/catch` would reduce that down to one `try/catch` for the stream and allow passing the error to the stream callback.

**Comment by erikkemperman** [comment]
> it looks like the calls to the value-of-function methods should be wrapped with try/catch to ensure any errors from user-defined functions are caught and passed to the stream's callback.

@doowb I happened to notice the same thing, and currently there are koalas/value-or-function tandems currently all over the place. These potential throws would have to be addressed if option handling were revisited (e.g. centralized).

**Comment by phated** [comment]
@doowb I believe thrown errors inside streams are caught by the domain and surfaced (damned domain magic).

I need to understand your use case; Does it __require__ a sync API?  I'd like to keep this an async API (future looking) if at all possible but I know a lot of integration points might need sync APIs.

@erikkemperman I'd like to centralize because the current scattering in vinyl-fs is scary and hard to document (but that belongs in vinyl-fs).

**Comment by phated** [comment]
Every time I look at this library, it makes me sick to my stomach.  I **really** dislike the API and it does so little.  😭 😭 😭

**Comment by erikkemperman** [comment]
I feel your pain. Well, maybe not to my stomach, but you know. It seems wrong somehow to introduce a disjunct module in order to make vinyl-fs skip some part of its work...

If I remember correctly, @doowb, you guys toyed with a `write` option to dest, much like src has a `read` option? That seems like a reasonable API, what were the difficulties there?

**Comment by phated** [comment]
Hey @doowb, this module is actually being deprecated.  If you end up making a module like you are looking for, let me know and I might use it in vinyl-fs.
