### ISSUE TITLE
Don't leak `flag` attribute on vinyl

### ISSUE THREAD

**Issue by erikkemperman** [gulpjs/vinyl-prepare#2]
@phated I figured I might as well go ahead and link to the experiment I mentioned in the value-or-function [issue](https://github.com/gulpjs/value-or-function/pull/5#issuecomment-240514273).

https://github.com/erikkemperman/vinyl-prepare/commits/refactor-prepare-write
https://github.com/erikkemperman/vinyl-fs/commits/refactor-prepare-write

It all started when I noticed that `prepareWrite` (and now `vinyl-prepare`) attached a `flag` attribute to the vinyl,
https://github.com/gulpjs/vinyl-prepare/blob/master/index.js#L47

This seemed to me to be a symptom of the options not being available in the right places (the `flag` attribute is completely determined by the `overwrite` option).

At the same time you guys started to split stuff into `vinyl-prepare` and so I merged my attempt at refactoring options processing (in particular, getting rid of this flag attribute) with that effort.

It needs work (tests, primarily) and I have some more ideas, but probably better to solicit feedback before I waste time on potential dead ends.

I also have half-baked work in progress to do a similar split for `src`, but I guess it would be easier to get the `dest` part more or less settled first, and then tackle `src` in the same way?

**Comment by phated** [comment]
I'm not sure if "leaking" the flag attribute it bad.  It allows us to have special logic in prepare that consumers can use where they see fit.  It doesn't make sense for people to duplicate that logic over and over in other vinyl adapters.

**Comment by erikkemperman** [comment]
If I understand correctly, I guess I would argue that such cases should be handled by adding to the options object (which I propose be returned by `vinyl-prepare`) and not the vinyl. The `flag` attribute is not actually a good example of "special logic", because it is just a simple function of `overwrite` and doesn't add any useful for consumers, I don't think. But maybe I am missing the point.

**Comment by phated** [comment]
Streaming an `options` object won't work because the next processor in the pipeline wouldn't receive the file.  `vinyl-prepare` would then become a callback-based API which I'm not too fond of.

I think flag is actually appropriate.  For simplicity's sake, let's evaluate a vinyl adapter for AWS.  Let's say AWS requires you to delete a file before writing a file with the same name.  So you do `vinylPrepare({ overwrite: true }).pipe(aws.dest())` and the `aws.dest()` method looks at the `flag` property and determines whether or not to delete before writing.

**Comment by erikkemperman** [comment]
I'm not proposing to stream options... Am I?

Rather I thought to expose the processing of options (mostly through `value-or-function`) separately, and use that from within streams, e.g.
https://github.com/erikkemperman/vinyl-fs/blob/refactor-prepare-write/lib/dest/write-contents/index.js#L20
Including from within the `prepare.write` stream,
https://github.com/erikkemperman/vinyl-prepare/blob/refactor-prepare-write/index.js#L34

Something like an AWS adapter would use the same pattern. BTW, does it make more sense for such an adapter to consume `flag` compared to just looking at `options.overwrite` if it has the latter easily available from this helper function off `vinyl-prepare`?

**Comment by phated** [comment]
> handled by adding to the options object (which I propose be returned by vinyl-prepare) and not the vinyl

Sorry, it seems like that means streaming the options.

The reason that `flag` is used is due to vinyl being a virtual file abstraction, which tries to mirror *nix-style files and file operations.  I'm not sure I like switching that to the `overwrite` flag directly.

**Comment by erikkemperman** [comment]
Yeah, I see how that is confusing, it may be slightly awkward to have some properties of the `vinyl-prepare` export be streams and some others just helper functions. Would it be silly to just attach the whole processed options (per vinyl, with the return value of any options which were provided as functions)?

Do you think folks are already actually expecting `flag`? Unless I missed something it's not currently a documented vinyl property? Neither is `overwrite`, obviously, but that's clearly a `vinyl-fs` specific option (which other adapters could co-opt if available from a shared module like `vinyl-prepare`).

**Comment by erikkemperman** [comment]
@phated Sorry I left this hanging a bit, got distracted by some stuff at work.

So I was wondering if, even if `flag` is deemed to be a useful property to attach to the vinyl, if my structural changes might still make some sense.

But maybe first the question should be to what extent, if at all, the processed options ought to be available for outside observers (callers of `vinyl-prepare`) -- which is partly where I was going with this.

**Comment by phated** [comment]
I have a feeling people might rely on that `flag` property, even though it's undocumented.  Since we are pushing into a major release, we could "break" it by removing it.  I believe all options passed to `vinyl-prepare.*` should make changes to the vinyl object, otherwise the option didn't make any sense to exist.

I want to keep `vinyl-prepare` only return streams and have export parity with `vinyl-fs` (`.src`, `.dest`, `.symlink`).  Now that I think about it, `.write` in vinyl-prepare should probably be called `.dest` because I need a `.symlink` for special symlink logic.

Not sure if that helped or was just rambling.

Aside: do you think flag would fit better on an "enchanced stats" object?

**Comment by erikkemperman** [comment]
To be clear, I'm not against the flag property per se, it just looked to me like it was added only as a slightly lazy hack to get at the overwrite option from within the writeXxx modules. As such, it's currently also specific to vinyl-fs.

I'm not sure if it should be in stat though, I think it might be better to keep stat close to node's fs.Stats?

About the options, there are some that are "global", i.e. not (currently) evaluated per vinyl even if they're provided as a function value. For `dest` there's the sourcemaps option, and for `src` there are some globals too. And even some per-vinyl options don't clearly translate to properties on the vinyl, I think, such as `read`. 

But maybe those are not relevant for people calling vinyl-prepare separately?

I agree it would be better to use `dest` and `src` instead of `write` and `read` here.

**Comment by phated** [comment]
All of the options need to be normalized per-file, including sourcemaps and the options in src. I thought that's what these issues were working towards. I have an open issue on gulp-sourcemaps for a needed feature to fully implement.

**Comment by erikkemperman** [comment]
Ah, I was unaware of that gulp-sourcemaps issue, which I'm guessing is [this one](https://github.com/floridoo/gulp-sourcemaps/issues/208). It's just that I noticed that the sourcemaps option was left out of your initial splitting stuff into vinyl-prepare and isn't normalized per file, which I thought kind of made sense for that option for some reason.

That would then just leave the through2 options as "global" in this sense (not a great term for it, I know) but those are probably out of scope here.

Well, for this particular issue I guess I moved in the wrong direction then -- I made the options available to the writeXxx modules, in the same way as they are in `src`, but if the idea is for each of the options to be reflected on the vinyl object by vinyl-prepare there should not be a need for that (and eventually neither should it be needed in `src`).

The only remaining changes I made here that may or may not be somewhat useful still are that I made `writeContents` a stream, and that I merged the logic `saveFile` stream into the `writeFile` stream... Any thoughts on those?

https://github.com/erikkemperman/vinyl-fs/commit/c23532ec92ca93d3819bba955e2d5d2ada1c0550
https://github.com/erikkemperman/vinyl-fs/commit/75def5851ad67586a9c223cd4c253cfc9f9ec62f

**Comment by phated** [comment]
@erikkemperman I'll keep those commits in mind but I was actually in the process of turning `mkdirp` into a stream; however, I'm still not sure it's the best way to do it and maybe yours is better.  Let me think on it.

**Comment by phated** [comment]
I think we are moving `filter-since` down into glob-stream but I haven't dug into that more (ref https://github.com/gulpjs/glob-stream/issues/66) but other than that, I agree.

**Comment by erikkemperman** [comment]
All right, I'll keep that in mind, thanks. The issue of splitting off vinyl-prepare started with a use case for `dest`, if I'm not mistaken -- can we think of one for `src`?

**Comment by phated** [comment]
I can't think of a specific use case for `src`, but generally, I want people to be able to build vinyl-fs-feature-parity vinyl adapters using this module + custom read/write logic.

**Comment by phated** [comment]
With the changes I am experimenting with in https://github.com/gulpjs/vinyl-fs/pull/239, I think we can stop leaking this attribute.

**Comment by erikkemperman** [comment]
I came across this again as well -- and was thinking it's very unlikely people depend on this property being on the vinyl, since it only ever became exposed post-`dest`.

**Comment by phated** [comment]
This has been solved in vinyl-fs master.
