### ISSUE TITLE
publish as beta or something similar?

### ISSUE THREAD

**Issue by jonschlinkert** [gulpjs/vinyl-prepare#8]
@phated just noticed this wasn't published, but I think there is enough to justify publishing. Would make it easier for devs to test and give feedback (and make sure you don't lose the name. you never know..)

**Comment by phated** [comment]
Trying to wrap up a couple things and release a `0.1.0`

**Comment by phated** [comment]
@jonschlinkert this is done. published what we currently have as 0.1.0 but it still needs a lot of work.
