### ISSUE TITLE
dest pathing logic

### ISSUE THREAD

**Issue by jonschlinkert** [gulpjs/vinyl-prepare#9]
We have a need for [this logic](https://github.com/gulpjs/vinyl-prepare/blob/master/index.js#L35-L52) in a sync function that we can use on a cloned `file` object. You might be able to suggest a better way to do what we need, so I'll try to explain the problem we're having and go from there.

- typically in builds the `dest` path doesn't need to be calculated until writing to the fs, but we need it before rendering templates, so we can calculate relative links, pagination, permalinks, etc (in assemble, verb, generate, update and some other libs). There are probably other user cases where this is necessary.
- to ensure that paths are correct and exactly the same on the context for templates as they are when files are written out by `vfs.dest()`, we'd like to find a way to do this using the same library, or at least the same logic and conventions as vinyl/gulp, so we can always defer to vinyl for best practices
- however, we can't use `vinyl-prepare` as is, because it returns a stream, and is async.  (edit: we want it to be sync so it can be used in template helpers or wherever it's needed, and it since it's not necessary to be async)

If all of this makes sense, how would you feel about splitting [this path logic](https://github.com/gulpjs/vinyl-prepare/blob/master/index.js#L35-L52), into a library? so that we can ensure that we (and anyone else who needs this) are always using the same logic to prepare destination paths as `vinyl-prepare`. 

cc @doowb

**Comment by phated** [comment]
I really don't think we can implement this as a sync interface.  We are going to be integrating sourcemap support and possibly other things that are async APIs.

Why do you require a sync interface?

**Comment by jonschlinkert** [comment]
> I really don't think we can implement this as a sync interface.

We only need the path logic, which is effectively this part:

```js
var cwd = path.resolve(options.cwd);
var outFolderPath = string(outFolder, file);
var basePath = path.resolve(cwd, outFolderPath);
var writePath = path.resolve(basePath, file.relative);

file.cwd = cwd;
file.base = path.normalize(basePath + path.sep);
file.path = writePath;
```

which is all sync besides the error callback [on line 39](https://github.com/gulpjs/vinyl-prepare/blob/master/index.js#L35-L52). If we externalized the logic, there is no reason we couldn't expose both sync and async methods to do that part, so that the error is still propagated to the callback and we can avoid doing a try-catch. 

> Why do you require a sync interface?

It's a nice-to-have, not need-to-have. If we calculate paths in helpers inside templates for sitemaps, permalinks, navigation, etc. sync would be nice since most template engines do not have async helper support. But we can get by with a plugin or middleware that does this before rendering. 

The main point is that we need to do dest calculations right up front, before any plugins are run (this will be true for every site generator or similar static web project where relative paths are calculated, there is no getting around it).

Really I totally understand if you would rather keep it as-is. I'd like to keep parity with this library, but I can just create a new lib and do it the way we need it if it doesn't make sense here - it's not a ton of logic anyway. No worries either way.

**Comment by jonschlinkert** [comment]
fwiw for now I'm going to create a shim library that I can use to do this, since we need it now. 

If you decide to break it out, I'll update the logic to be the same as here, and I can deprecate, repurpose or move that library under your control, whatever makes sense.

**Comment by phated** [comment]
@jonschlinkert That's disconcerting.  The whole point of creating this library was because @doowb opened https://github.com/gulpjs/vinyl-fs/issues/193 which has considerably slowed down vinyl-fs@next.  The idea was to have this common library for us to use.

**Comment by jonschlinkert** [comment]
> The whole point of creating this library was because @doowb opened gulpjs/vinyl-fs#193 

I forgot about the history and the issue that @doowb opened, since that was a completely unrelated use case, where async handling would have been fine. We still need this, and can use it as-is once it's published. I'm just trying to solve a different, specific use case that would be easier to do if this library didn't return a stream. 

With all of that said, I'm not sure why it's disconcerting. We're trying to find ways to work with these libraries, and we're sharing our use cases in an effort to collaborate instead of just going in a different direction. 

> which has considerably slowed down vinyl-fs@next. The idea was to have this common library for us to use.

I want our ecosystem to align with yours, and fwiw I'm willing to take some extra steps on our end to ensure that we're doing what we can to make that happen, and I know that you've also gone out of your way to help us, even though it might not benefit your ecosystem as much as it does ours, and I appreciate that a lot. We won't be offended at all if you decide not to change anything here. Like I said, we will still need this library and will use it, either way - and we'll try to figure out how to use this for the new use case I created this issue about.

**Comment by phated** [comment]
Sorry, that was strong wording.  I was under the impression that your usage changed from the linked issue.  I'll think more on the pathing stuff.

**Comment by phated** [comment]
@jonschlinkert what module did you end up creating for this? Just so we have a reference

**Comment by jonschlinkert** [comment]
I didn't create a module for it. I'll link it here if I do.

**Comment by phated** [comment]
Hey @jonschlinkert, this module is actually being deprecated.  If you end up making a module like you are looking for, let me know and I might use it in vinyl-fs.
